customer:
  target: dev
  outputs:
    dev:
      dataset: dbt_dev
      job_execution_timeout_seconds: 7000  # 2 hours
      job_retries: 1
      location: europe-west2
      method: oauth
      priority: interactive
      project: plum-platform-staging
      threads: 4
      type: bigquery
      maximum_bytes_billed: 3200000000000  # ~3.2 TB
      execution_project: plum-platform-staging
rental:
  target: dev
  outputs:
    dev:
      type: postgres
      # host: dummy_host
      # user: dummy_user
      # pass: dummy_pass
      # port: 5432
      # dbname: dummy_db
      schema: public
      threads: 1