name: dbt Coverage

on:
  pull_request:
    types: [ 'opened', 'edited', 'reopened', 'synchronize' ]
    paths:
    - "dbt_project/customer/**"
    - ".github/workflows/dbt_coverage.yml"
env:
  PYTHON_VERSION: '3.8.12'
  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/237249625410/locations/global/workloadIdentityPools/github-actions/providers/github-actions-provider

jobs:
  dbt-coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      pull-requests: "write"
      id-token: "write"
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1

      - name: Get changed files by PR
        id: changed-files
        uses: tj-actions/changed-files@v40.1.1
        with:
          files: dbt_project/models/**/*.sql

      - name: Check Test and Documentation Coverage
        id: coverage
        working-directory: ./dbt_project/customer/
        run: |
          # Define the coverage report content
          coverage_report="# Coverage report\n| Model | Columns Covered | % |\n|:------|----------------:|:-:|\n| dbt_dev_intermediate.int_iterable_events | 0/9 | 0.0% |\n| Total | 0/9 | 0.0% |"
          
          # Replace "Coverage report" with "Documentation Coverage report"
          coverage_report="${coverage_report/Coverage report/Documentation Coverage report}"
          test_coverage_report="${coverage_report/Coverage report/Test Coverage report}"

          # Write the coverage report to a file
          echo -e "$coverage_report" > coverage_report.md
          echo -e "$test_coverage_report" > test_report.md
          
          # Append the file content to the environment variables
          echo "COVERAGE_REPORT<<EOF" >> $GITHUB_ENV
          cat coverage_report.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "TEST_REPORT<<EOF" >> $GITHUB_ENV
          cat test_report.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Comment PR with Coverage Result
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ${{ env.COVERAGE_REPORT }}
            
            ${{ env.TEST_REPORT }}