name: dbt Coverage

on:
  pull_request:
    types: [ 'opened', 'edited', 'reopened', 'synchronize' ]
    paths:
    - "dbt_project/customer/**"
    - ".github/workflows/dbt_coverage.yml"
env:
  PYTHON_VERSION: '3.8.12'
  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/237249625410/locations/global/workloadIdentityPools/github-actions/providers/github-actions-provider

jobs:
  dbt-coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      pull-requests: "write"
      id-token: "write"
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1

      - name: Get changed files by PR
        id: changed-files
        uses: tj-actions/changed-files@v40.1.1
        with:
          files: dbt_project/models/**/*.sql

      - name: Check Test and Documentation Coverage
        id: coverage
        working-directory: ./dbt_project/customer/
        run: |
          # Define the coverage report content
    # Define the coverage report content
          coverage_report="# Coverage report\n| Model | Columns Covered | % |\n|:------|----------------:|:-:|\n| dbt_dev_intermediate.int_iterable_events | 0/9 | 0.0% |\n| Total | 0/9 | 0.0% |"
          
          # Encode newlines for GitHub Actions output
          coverage_report="${coverage_report//'%'/'%25'}" # Escape %
          coverage_report="${coverage_report//$'\n'/'%0A'}" # Replace newline characters
          coverage_report="${coverage_report//$'\r'/'%0D'}" # Replace carriage return characters
          
          # Set the outputs
          echo "::set-output name=doc_coverage_output::$coverage_report"
          echo "::set-output name=test_coverage_output::$coverage_report"

      - name: Comment PR with Coverage Result
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            **Documentation coverage output:**
            ${{ fromJSON(steps.coverage.outputs.doc_coverage_output) }}
            
            **Test coverage output:**
            ${{ fromJSON(steps.coverage.outputs.test_coverage_output) }}
