name: dbt Coverage

on:
  pull_request:
    types: [ 'opened', 'edited', 'reopened', 'synchronize' ]
    paths:
    - "dbt_project/customer/**"
    - ".github/workflows/dbt_coverage.yml"
env:
  PYTHON_VERSION: '3.8.12'
  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/237249625410/locations/global/workloadIdentityPools/github-actions/providers/github-actions-provider

jobs:
  dbt-coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      pull-requests: "write"
      id-token: "write"
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1

      - name: Get changed files by PR
        id: changed-files
        uses: tj-actions/changed-files@v40.1.1
        with:
          files: dbt_project/models/**/*.sql

      - name: Check Test and Documentation Coverage
        id: coverage
        working-directory: ./projects/plum/
        run: |
          coverage_report="| Model | Columns Covered | % |\n|:------|----------------:|:-:|\n| dbt_dev_intermediate.int_iterable_events | 0/9 | 0.0% |\n| Total | 0/9 | 0.0% |"
          echo -e "# Coverage report\n${coverage_report}" > coverage_report.md
          echo -e "# Coverage report\n${coverage_report}" > test_report.md
          echo "::set-output name=coverage_report_path::$(pwd)/coverage_report.md"
          echo "::set-output name=test_report_path::$(pwd)/test_report.md"

      - name: Comment PR with Coverage Result
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            **Documentation coverage output:**
            ```
            $(cat ${{ steps.coverage.outputs.coverage_report_path }})
            ```
            
            **Test coverage output:**
            ```
            $(cat ${{ steps.coverage.outputs.test_report_path }})
            ```